version: '3'

volumes:
  mysql_data:
    driver: local

  minio_data:
    driver: local

services:
  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_USER: adama
      MYSQL_PASSWORD: password
    ports:
      - "33061:3306"


  minio:
    image: docker.io/bitnami/minio:2023
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'

  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_REPLICATION_MODE=master


  bookstore:
    image: adama93/bookstore:latest
    container_name: bookstore
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bookstore
    depends_on:
      - mysql
      - minio
      - redis

