spring:
  profiles:
    active: local


resilience4j.ratelimiter:
  instances:
    backendA:
      limitForPeriod: 10
      limitRefreshPeriod: 5s
      timeoutDuration: 60s
      registerHealthIndicator: true
      eventConsumerBufferSize: 100


#togglz:
#  features:
#    CREATE_BOOK:
#      enabled: true
#  features-file: 'feature.properties'
#  console:
#    secured: false
#management:
#  endpoints:
#    web:
#      exposure:
#        include: 'togglz'

management:
  endpoint:
    health:
      show-details: ALWAYS
  health:
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"