# Server properties
server:
  port: 9090

#Spring Properties
spring:
  application:
    name: bookstore

  # Jpa Properties
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?autoReconnect=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 20
      minimum-idle: 8
      pool-name: myPool
      connection-test-query: select 1 from dual


  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true

  # Spring Session properties

  devtools:
    restart:
      enabled: true


# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
