spring:
  profiles:
    active: local

togglz:
  features:
    CREATE_BOOK:
      enabled: true
  features-file: 'feature.properties'
  console:
    secured: false
management:
  endpoints:
    web:
      exposure:
        include: 'togglz'