# Server properties
server:
  port: 9090

#Spring Properties
spring:
  application:
    name: bookstore

  # Jpa Properties
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    user: root
    password:
    group: true
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    baseline-on-migrate: true


  # Spring Session properties

  devtools:
    restart:
      enabled: true