version: '3'

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_USER: adama
      MYSQL_PASSWORD: password
    ports:
      - "33061:3306"